import React from 'react';
import SignInFrom from './components/SignInFrom';

export const metadata = {
  title: "Sign In",
  description: "Generated by create next app",
};

const SignInPage = () => {
    return (
        <div className='py-32'>
            <SignInFrom/>
        </div>
    );
};

export default SignInPage;