import React from 'react';
import CartTable from './components/CartTable';

export const metadata = {
  title: "My Cart",
  description: "Generated by create next app",
};

const CartPage = () => {
    return (
        <div className='pt-24'>
            <CartTable/>
        </div>
    );
};

export default CartPage;