import SideBar from "./components/SideBar";

export const metadata = {
  title: "My Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <div className="flex min-h-screen">
      {/* Sidebar */}
      <div className="md:fixed h-full md:w-64">
        <SideBar />
      </div>

      {/* Main content - offset by sidebar width */}
      <main className="flex-1 ">
        <section className="md:ml-64">{children}</section>
      </main>
    </div>
  );
}
