import ProductTable from './components/ProductTable';

export const metadata = {
  title: "My Products",
  description: "Generated by create next app",
};

const MyProductPage = () => {
    
    return (
        <div className='pt-22'>
            <ProductTable />
        </div>
    );
};

export default MyProductPage;