
import React from 'react';
import AddFrom from './component/AddFrom';

export const metadata = {
  title: "Add Product",
  description: "Generated by create next app",
};

const AddProductPage = () => {
    return (
        <div className='py-32'>
           
            <AddFrom/>
        </div>
    );
};

export default AddProductPage;