import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import NextAuthProvider from "@/Providers/NextAuthProvider";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Tech Trade | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
          <header>
            <NavBar />
          </header>
          <main className="max-w-screen-xl mx-auto px-4 min-h-[calc(100vh-280px)]">{children}</main>
          <Footer/>
        </NextAuthProvider>
      </body>
    </html>
  );
}
