import React from 'react';
import SignUpFrom from './components/SignUpFrom';

export const metadata = {
  title: "Sign Up",
  description: "Generated by create next app",
};

const SignUpPage = () => {
    return (
        <div className=''>
            
            <SignUpFrom/>
        </div>
    );
};

export default SignUpPage;