
import React from 'react';
import DashboardAddFrom from './component/AddFrom';


export const metadata = {
  title: "Add Product",
  description: "Generated by create next app",
};

const DashboardAddProduct = () => {
    return (
        <div className='py-32'>
           
           <DashboardAddFrom/>
        </div>
    );
};

export default DashboardAddProduct;